import { BloodResultsModel } from '../db/models/bloodResults.ts';
import { AthleteModel } from '../db/models/athletes.ts';

// Mapping between blood results data names and actual athlete codes in the database
const nameToAthleteCodeMap: { [key: string]: string } = {
  "Lezane Botto": "ATH012",
  "Marquel Miller": "ATH014",
  "George Evans": "ATH007",
  "Ethan Gordon": "ATH006",
  "Dijan Labuschagne": "ATH005",
  "Luke Prest": "ATH013",
  "Christiaan Tromp": "ATH004",
  "Ethan Isaacs": "ATH008",
  "Bowen Bezuidenhout": "ATH003", // Different spelling: Bezuidenhoudt in DB
  "James Nero": "ATH009",
  "Aden Oerson": "ATH001",
  "Aldrich Wichman": "ATH002",
  "Juane De Klerk": "ATH011", // Different spelling: Juanre De Klerk in DB
  // Names not found in database - will be skipped:
  // "Torbyn Visser", "Steffan De Jongh", "Emile Damant", "Souheil Tahiri",
  // "Ritchie Mitchell", "Nicholas Fritz", "Matthew S Jacobs", "Michael Maseti",
  // "Riego Heath"
};
// Blood results data from the CSV
const bloodResultsData = [
  {
    name: "Lezane Botto",
    code: 1,
    cortisol_nmol_l: 480,
    vitamin_d: 32,
    testosterone: 44.5,
    ck: 149,
    fasting_glucose: 5.2,
    hba1c: 5.6,
    hba1c_ifcc: 38,
    estimated_average_glucose: 6.3,
    urea: 5.4,
    creatinine: 105,
    egfr: 88,
    uric_acid: 0.27,
    s_glutamyl_transferase: 10,
    s_alanine_transaminase: 11,
    s_aspartate_transaminase: 24,
    lactate_dehydrogenase: 161,
    calcium_adjusted: 2.25,
    calcium_measured: 2.45,
    magnesium: 0.84,
    albumin_bcg: 50,
    c_reactive_protein: 1, // < 1.0
    total_protein: 76,
    esr: null,
    erythrocyte_count: 5.35,
    hemoglobin: 15.8,
    hematocrit: 0.47,
    mcv: 87.7,
    mch: 29.5,
    mchc: 33.7,
    rdw: 12.2,
    leucocyte_count: 7.89,
    neutrophils_pct: 49.4,
    neutrophil_absolute_count: 3.90,
    lymphocytes_pct: 40.4,
    lymphocytes_absolute_count: 3.19,
    monocytes_pct: 6.6,
    monocytes_absolute_count: 0.52,
    eosinophils_pct: 3.2,
    eosinophils_absolute_count: 0.25,
    basophils_pct: 0.4,
    basophils_absolute_count: 0.03,
    nlr: 1.22,
    platelets: 289
  },
  {
    name: "Torbyn Visser",
    code: 2,
    cortisol_nmol_l: 366,
    vitamin_d: 41,
    testosterone: null,
    ck: 259,
    fasting_glucose: 4.3,
    hba1c: 5.2,
    hba1c_ifcc: 33,
    estimated_average_glucose: 5.7,
    urea: 6.1,
    creatinine: 90,
    egfr: 89, // > 89
    uric_acid: 0.34,
    s_glutamyl_transferase: 30,
    s_alanine_transaminase: 32,
    s_aspartate_transaminase: 29,
    lactate_dehydrogenase: null,
    calcium_adjusted: 2.30,
    calcium_measured: 2.50,
    magnesium: 0.90,
    albumin_bcg: 50,
    c_reactive_protein: 1, // < 1.0
    total_protein: 75,
    esr: null,
    erythrocyte_count: 5.38,
    hemoglobin: 16.5,
    hematocrit: 0.49,
    mcv: 91.6,
    mch: 30.7,
    mchc: 33.5,
    rdw: 11.8,
    leucocyte_count: 5.98,
    neutrophils_pct: 52.2,
    neutrophil_absolute_count: 3.12,
    lymphocytes_pct: 38.5,
    lymphocytes_absolute_count: 2.30,
    monocytes_pct: 8.0,
    monocytes_absolute_count: 0.48,
    eosinophils_pct: 0.8,
    eosinophils_absolute_count: 0.05,
    basophils_pct: 0.5,
    basophils_absolute_count: 0.03,
    nlr: 1.36,
    platelets: 258
  },
  {
    name: "Steffan De Jongh",
    code: 3,
    cortisol_nmol_l: 280,
    vitamin_d: 27,
    testosterone: 20.6,
    ck: 95,
    fasting_glucose: 5.0,
    hba1c: null,
    hba1c_ifcc: null,
    estimated_average_glucose: null,
    urea: 5.7,
    creatinine: 83,
    egfr: 89, // > 89
    uric_acid: 0.41,
    s_glutamyl_transferase: 15,
    s_alanine_transaminase: 22,
    s_aspartate_transaminase: 24,
    lactate_dehydrogenase: 231,
    calcium_adjusted: 2.24,
    calcium_measured: 2.44,
    magnesium: 0.90,
    albumin_bcg: 50,
    c_reactive_protein: 1, // < 1.0
    total_protein: 79,
    esr: 3,
    erythrocyte_count: 5.30,
    hemoglobin: 15.8,
    hematocrit: 0.47,
    mcv: 89.1,
    mch: 29.8,
    mchc: 33.5,
    rdw: 12.7,
    leucocyte_count: 6.82,
    neutrophils_pct: 54.3,
    neutrophil_absolute_count: 3.70,
    lymphocytes_pct: 32.4,
    lymphocytes_absolute_count: 2.21,
    monocytes_pct: 10.6,
    monocytes_absolute_count: 0.72,
    eosinophils_pct: 2.3,
    eosinophils_absolute_count: 0.16,
    basophils_pct: 0.4,
    basophils_absolute_count: 0.03,
    nlr: 1.67,
    platelets: 278
  },
  {
    name: "Marquel Miller",
    code: 4,
    cortisol_nmol_l: 401,
    vitamin_d: 32,
    testosterone: 20.4,
    ck: 1423,
    fasting_glucose: 4.7,
    hba1c: 5.8,
    hba1c_ifcc: 40,
    estimated_average_glucose: 6.6,
    urea: 7.6,
    creatinine: 125,
    egfr: 72,
    uric_acid: 0.37,
    s_glutamyl_transferase: 12,
    s_alanine_transaminase: 77,
    s_aspartate_transaminase: 66,
    lactate_dehydrogenase: 343,
    calcium_adjusted: 2.32,
    calcium_measured: 2.46,
    magnesium: 0.83,
    albumin_bcg: 47,
    c_reactive_protein: 10.1,
    total_protein: 69,
    esr: null,
    erythrocyte_count: 5.37,
    hemoglobin: 13.8,
    hematocrit: 0.43,
    mcv: 79.9,
    mch: 25.7,
    mchc: 32.2,
    rdw: 14.1,
    leucocyte_count: 6.73,
    neutrophils_pct: 43.0,
    neutrophil_absolute_count: 2.89,
    lymphocytes_pct: 47.0,
    lymphocytes_absolute_count: 3.16,
    monocytes_pct: 10.0,
    monocytes_absolute_count: 0.67,
    eosinophils_pct: 0.0,
    eosinophils_absolute_count: 0.00,
    basophils_pct: 0.0,
    basophils_absolute_count: 0.00,
    nlr: 0.91,
    platelets: 326
  },
  {
    name: "Emile Damant",
    code: 5,
    cortisol_nmol_l: 512,
    vitamin_d: null,
    testosterone: null,
    ck: 279,
    fasting_glucose: 4.4,
    hba1c: 5.1,
    hba1c_ifcc: 32,
    estimated_average_glucose: 5.5,
    urea: 11.0,
    creatinine: 143,
    egfr: 59,
    uric_acid: 0.44,
    s_glutamyl_transferase: 16,
    s_alanine_transaminase: 26,
    s_aspartate_transaminase: 29,
    lactate_dehydrogenase: 212,
    calcium_adjusted: 2.30,
    calcium_measured: 2.50,
    magnesium: 0.94,
    albumin_bcg: 50,
    c_reactive_protein: 1, // < 1.0
    total_protein: 72,
    esr: null,
    erythrocyte_count: 5.62,
    hemoglobin: 16.7,
    hematocrit: 0.48,
    mcv: 85.4,
    mch: 29.7,
    mchc: 34.8,
    rdw: 11.3,
    leucocyte_count: 4.85,
    neutrophils_pct: 44.0,
    neutrophil_absolute_count: 2.13,
    lymphocytes_pct: 44.5,
    lymphocytes_absolute_count: 2.16,
    monocytes_pct: 8.2,
    monocytes_absolute_count: 0.40,
    eosinophils_pct: 2.1,
    eosinophils_absolute_count: 0.10,
    basophils_pct: 1.2,
    basophils_absolute_count: 0.06,
    nlr: 0.99,
    platelets: 184
  },
  {
    name: "George Evans",
    code: 6,
    cortisol_nmol_l: 258,
    vitamin_d: null,
    testosterone: 30.6,
    ck: 196,
    fasting_glucose: 5.1,
    hba1c: 5.3,
    hba1c_ifcc: 34,
    estimated_average_glucose: 5.8,
    urea: 7.4,
    creatinine: 106,
    egfr: 88,
    uric_acid: 0.39,
    s_glutamyl_transferase: 15,
    s_alanine_transaminase: 18,
    s_aspartate_transaminase: 22,
    lactate_dehydrogenase: 194,
    calcium_adjusted: 2.27,
    calcium_measured: 2.47,
    magnesium: 0.87,
    albumin_bcg: 50,
    c_reactive_protein: 1.3,
    total_protein: 81,
    esr: null,
    erythrocyte_count: 5.37,
    hemoglobin: 16.3,
    hematocrit: 0.48,
    mcv: 89.6,
    mch: 30.4,
    mchc: 33.9,
    rdw: 13.1,
    leucocyte_count: 8.59,
    neutrophils_pct: 36.2,
    neutrophil_absolute_count: 3.11,
    lymphocytes_pct: 51.3,
    lymphocytes_absolute_count: 4.41,
    monocytes_pct: 9.2,
    monocytes_absolute_count: 0.79,
    eosinophils_pct: 2.6,
    eosinophils_absolute_count: 0.22,
    basophils_pct: 0.7,
    basophils_absolute_count: 0.06,
    nlr: 0.71,
    platelets: 269
  },
  {
    name: "Ethan Gordon",
    code: 7,
    cortisol_nmol_l: 286,
    vitamin_d: 32,
    testosterone: 22.6,
    ck: 254,
    fasting_glucose: 4.6,
    hba1c: 5.2,
    hba1c_ifcc: 33,
    estimated_average_glucose: 5.7,
    urea: 8.0,
    creatinine: 95,
    egfr: 89, // > 89
    uric_acid: 0.33,
    s_glutamyl_transferase: 27,
    s_alanine_transaminase: 24,
    s_aspartate_transaminase: 24,
    lactate_dehydrogenase: 209,
    calcium_adjusted: 2.26,
    calcium_measured: 2.50,
    magnesium: 0.94,
    albumin_bcg: 52,
    c_reactive_protein: 1, // < 1.0
    total_protein: 79,
    esr: null,
    erythrocyte_count: 5.25,
    hemoglobin: 15.8,
    hematocrit: 0.48,
    mcv: 91.8,
    mch: 30.1,
    mchc: 32.8,
    rdw: 12.3,
    leucocyte_count: 7.40,
    neutrophils_pct: 58.7,
    neutrophil_absolute_count: 4.34,
    lymphocytes_pct: 30.0,
    lymphocytes_absolute_count: 2.22,
    monocytes_pct: 9.7,
    monocytes_absolute_count: 0.72,
    eosinophils_pct: 1.2,
    eosinophils_absolute_count: 0.09,
    basophils_pct: 0.4,
    basophils_absolute_count: 0.03,
    nlr: 1.95,
    platelets: 324
  },
  {
    name: "Dijan Labuschagne",
    code: 8,
    cortisol_nmol_l: 738,
    vitamin_d: 42,
    testosterone: 32.1,
    ck: 149,
    fasting_glucose: 5.1,
    hba1c: 5.4,
    hba1c_ifcc: 36,
    estimated_average_glucose: 6.0,
    urea: 6.9,
    creatinine: 109,
    egfr: 84,
    uric_acid: 0.35,
    s_glutamyl_transferase: 23,
    s_alanine_transaminase: 18,
    s_aspartate_transaminase: 23,
    lactate_dehydrogenase: 197,
    calcium_adjusted: 2.33,
    calcium_measured: 2.57,
    magnesium: 0.90,
    albumin_bcg: 52,
    c_reactive_protein: 1, // < 1.0
    total_protein: 79,
    esr: null,
    erythrocyte_count: 5.06,
    hemoglobin: 16.1,
    hematocrit: 0.47,
    mcv: 93.7,
    mch: 31.8,
    mchc: 34.0,
    rdw: 11.8,
    leucocyte_count: 5.43,
    neutrophils_pct: 57.7,
    neutrophil_absolute_count: 3.13,
    lymphocytes_pct: 30.8,
    lymphocytes_absolute_count: 1.67,
    monocytes_pct: 9.9,
    monocytes_absolute_count: 0.54,
    eosinophils_pct: 0.9,
    eosinophils_absolute_count: 0.05,
    basophils_pct: 0.7,
    basophils_absolute_count: 0.04,
    nlr: 1.87,
    platelets: 268
  },
  {
    name: "Souheil Tahiri",
    code: 9,
    cortisol_nmol_l: 429,
    vitamin_d: 18,
    testosterone: 22.1,
    ck: 93,
    fasting_glucose: 4.4,
    hba1c: 5.3,
    hba1c_ifcc: 34,
    estimated_average_glucose: 5.8,
    urea: 7.5,
    creatinine: 82,
    egfr: 89, // > 89
    uric_acid: 0.36,
    s_glutamyl_transferase: 17,
    s_alanine_transaminase: 19,
    s_aspartate_transaminase: 24,
    lactate_dehydrogenase: 228,
    calcium_adjusted: 2.28,
    calcium_measured: 2.46,
    magnesium: 0.82,
    albumin_bcg: 49,
    c_reactive_protein: 1, // < 1.0
    total_protein: 77,
    esr: 1,
    erythrocyte_count: 5.18,
    hemoglobin: 16.0,
    hematocrit: 0.48,
    mcv: 93.4,
    mch: 30.9,
    mchc: 33.1,
    rdw: 12.7,
    leucocyte_count: 7.30,
    neutrophils_pct: 45.9,
    neutrophil_absolute_count: 3.35,
    lymphocytes_pct: 36.7,
    lymphocytes_absolute_count: 2.68,
    monocytes_pct: 10.4,
    monocytes_absolute_count: 0.76,
    eosinophils_pct: 6.0,
    eosinophils_absolute_count: 0.44,
    basophils_pct: 1.0,
    basophils_absolute_count: 0.07,
    nlr: 1.25,
    platelets: 264
  },
  {
    name: "Luke Prest",
    code: 10,
    cortisol_nmol_l: 229,
    vitamin_d: 65,
    testosterone: 14.8,
    ck: null,
    fasting_glucose: 5.2,
    hba1c: 5.4,
    hba1c_ifcc: 36,
    estimated_average_glucose: 6.0,
    urea: 4.8,
    creatinine: 86,
    egfr: 89, // > 89
    uric_acid: 0.30,
    s_glutamyl_transferase: 19,
    s_alanine_transaminase: 20,
    s_aspartate_transaminase: 28,
    lactate_dehydrogenase: 226,
    calcium_adjusted: null,
    calcium_measured: null,
    magnesium: null,
    albumin_bcg: null,
    c_reactive_protein: null,
    total_protein: null,
    esr: null,
    erythrocyte_count: 5.34,
    hemoglobin: 15.6,
    hematocrit: 0.46,
    mcv: 86.0,
    mch: 29.2,
    mchc: 34.0,
    rdw: 12.4,
    leucocyte_count: 8.69,
    neutrophils_pct: 59.0,
    neutrophil_absolute_count: 5.13,
    lymphocytes_pct: 28.2,
    lymphocytes_absolute_count: 2.45,
    monocytes_pct: 8.4,
    monocytes_absolute_count: 0.73,
    eosinophils_pct: 3.9,
    eosinophils_absolute_count: 0.34,
    basophils_pct: 0.5,
    basophils_absolute_count: 0.04,
    nlr: 2.09,
    platelets: 298
  },
  {
    name: "Ritchie Mitchell",
    code: 11,
    cortisol_nmol_l: 490,
    vitamin_d: 49,
    testosterone: 23.3,
    ck: 145,
    fasting_glucose: 5.3,
    hba1c: 5.7,
    hba1c_ifcc: 39,
    estimated_average_glucose: 6.5,
    urea: 6.5,
    creatinine: 89,
    egfr: 89, // > 89
    uric_acid: 0.48,
    s_glutamyl_transferase: 15,
    s_alanine_transaminase: 16,
    s_aspartate_transaminase: 26,
    lactate_dehydrogenase: 252,
    calcium_adjusted: 2.33,
    calcium_measured: 2.53,
    magnesium: 0.87,
    albumin_bcg: 50,
    c_reactive_protein: 1, // < 1.0
    total_protein: 79,
    esr: null,
    erythrocyte_count: 5.39,
    hemoglobin: 16.5,
    hematocrit: 0.48,
    mcv: 89.4,
    mch: 30.6,
    mchc: 34.2,
    rdw: 11.8,
    leucocyte_count: 7.69,
    neutrophils_pct: 53.5,
    neutrophil_absolute_count: 4.11,
    lymphocytes_pct: 29.4,
    lymphocytes_absolute_count: 2.26,
    monocytes_pct: 9.2,
    monocytes_absolute_count: 0.71,
    eosinophils_pct: 7.4,
    eosinophils_absolute_count: 0.57,
    basophils_pct: 0.5,
    basophils_absolute_count: 0.04,
    nlr: 1.82,
    platelets: 312
  },
  {
    name: "Christiaan Tromp",
    code: 12,
    cortisol_nmol_l: 280,
    vitamin_d: null,
    testosterone: 21.2,
    ck: 82,
    fasting_glucose: 5.3,
    hba1c: 5.2,
    hba1c_ifcc: 33,
    estimated_average_glucose: 5.7,
    urea: 6.4,
    creatinine: 80,
    egfr: 89, // > 89
    uric_acid: 0.34,
    s_glutamyl_transferase: 42,
    s_alanine_transaminase: 29,
    s_aspartate_transaminase: 15,
    lactate_dehydrogenase: 222,
    calcium_adjusted: 2.28,
    calcium_measured: 2.54,
    magnesium: 0.88,
    albumin_bcg: 53,
    c_reactive_protein: 3.1,
    total_protein: 79,
    esr: null,
    erythrocyte_count: 6.08,
    hemoglobin: 17.2,
    hematocrit: 0.51,
    mcv: 83.7,
    mch: 28.3,
    mchc: 33.8,
    rdw: 12.6,
    leucocyte_count: 15.01,
    neutrophils_pct: 73.5,
    neutrophil_absolute_count: 11.03,
    lymphocytes_pct: 18.1,
    lymphocytes_absolute_count: 2.71,
    monocytes_pct: 6.9,
    monocytes_absolute_count: 1.04,
    eosinophils_pct: 1.1,
    eosinophils_absolute_count: 0.17,
    basophils_pct: 0.4,
    basophils_absolute_count: 0.06,
    nlr: 4.07,
    platelets: 388
  },
  {
    name: "Ethan Isaacs",
    code: 13,
    cortisol_nmol_l: 410,
    vitamin_d: 14,
    testosterone: null,
    ck: 654,
    fasting_glucose: 4.2,
    hba1c: 5.1,
    hba1c_ifcc: 32,
    estimated_average_glucose: 5.5,
    urea: 5.6,
    creatinine: 108,
    egfr: 84,
    uric_acid: null,
    s_glutamyl_transferase: 22,
    s_alanine_transaminase: 17,
    s_aspartate_transaminase: 30,
    lactate_dehydrogenase: 338,
    calcium_adjusted: 2.28,
    calcium_measured: 2.48,
    magnesium: 1.01,
    albumin_bcg: 50,
    c_reactive_protein: 1.3,
    total_protein: 76,
    esr: null,
    erythrocyte_count: 5.44,
    hemoglobin: 15.8,
    hematocrit: 0.45,
    mcv: 83.3,
    mch: 29.0,
    mchc: 34.9,
    rdw: 11.6,
    leucocyte_count: 10.03,
    neutrophils_pct: 45.0,
    neutrophil_absolute_count: 4.51,
    lymphocytes_pct: 46.0,
    lymphocytes_absolute_count: 4.61,
    monocytes_pct: 7.0,
    monocytes_absolute_count: 0.70,
    eosinophils_pct: 2.0,
    eosinophils_absolute_count: 0.20,
    basophils_pct: 0.0,
    basophils_absolute_count: 0.00,
    nlr: 0.98,
    platelets: 316
  },
  {
    name: "Bowen Bezuidenhout",
    code: 14,
    cortisol_nmol_l: 327,
    vitamin_d: null,
    testosterone: 20.8,
    ck: 126,
    fasting_glucose: 4.7,
    hba1c: 5.5,
    hba1c_ifcc: 37,
    estimated_average_glucose: 6.2,
    urea: 8.8,
    creatinine: 103,
    egfr: 88,
    uric_acid: 0.45,
    s_glutamyl_transferase: 23,
    s_alanine_transaminase: 29,
    s_aspartate_transaminase: 28,
    lactate_dehydrogenase: 304,
    calcium_adjusted: 2.20,
    calcium_measured: 2.44,
    magnesium: 0.91,
    albumin_bcg: 52,
    c_reactive_protein: 1, // < 1.0
    total_protein: 80,
    esr: null,
    erythrocyte_count: 5.44,
    hemoglobin: 16.2,
    hematocrit: 0.47,
    mcv: 86.0,
    mch: 29.8,
    mchc: 34.6,
    rdw: 11.4,
    leucocyte_count: 5.25,
    neutrophils_pct: 51.0,
    neutrophil_absolute_count: 2.68,
    lymphocytes_pct: 34.0,
    lymphocytes_absolute_count: 1.79,
    monocytes_pct: 8.0,
    monocytes_absolute_count: 0.42,
    eosinophils_pct: 3.0,
    eosinophils_absolute_count: 0.16,
    basophils_pct: 0.0,
    basophils_absolute_count: 0.00,
    nlr: 1.50,
    platelets: 375
  },
  {
    name: "James Nero",
    code: 15,
    cortisol_nmol_l: 469,
    vitamin_d: null,
    testosterone: 27.9,
    ck: 378,
    fasting_glucose: 5.0,
    hba1c: 5.3,
    hba1c_ifcc: 34,
    estimated_average_glucose: 5.8,
    urea: 4.1,
    creatinine: 80,
    egfr: 89, // > 89
    uric_acid: 0.38,
    s_glutamyl_transferase: 33,
    s_alanine_transaminase: 37,
    s_aspartate_transaminase: 36,
    lactate_dehydrogenase: 277,
    calcium_adjusted: 2.28,
    calcium_measured: 2.44,
    magnesium: 0.84,
    albumin_bcg: 48,
    c_reactive_protein: 1, // < 1.0
    total_protein: 77,
    esr: null,
    erythrocyte_count: 5.63,
    hemoglobin: 16.3,
    hematocrit: 0.50,
    mcv: 88.8,
    mch: 29.0,
    mchc: 32.6,
    rdw: 12.0,
    leucocyte_count: 9.56,
    neutrophils_pct: 49.1,
    neutrophil_absolute_count: 4.68,
    lymphocytes_pct: 39.4,
    lymphocytes_absolute_count: 3.77,
    monocytes_pct: 7.9,
    monocytes_absolute_count: 0.76,
    eosinophils_pct: 3.2,
    eosinophils_absolute_count: 0.31,
    basophils_pct: 0.4,
    basophils_absolute_count: 0.04,
    nlr: 1.24,
    platelets: 144
  },
  {
    name: "Nicholas Fritz",
    code: 16,
    cortisol_nmol_l: 474,
    vitamin_d: 32,
    testosterone: 23.3,
    ck: 119,
    fasting_glucose: 4.6,
    hba1c: 5.3,
    hba1c_ifcc: 34,
    estimated_average_glucose: 5.8,
    urea: 5.7,
    creatinine: 98,
    egfr: 89, // > 89
    uric_acid: 0.45,
    s_glutamyl_transferase: 35,
    s_alanine_transaminase: 16,
    s_aspartate_transaminase: 21,
    lactate_dehydrogenase: 199,
    calcium_adjusted: 2.42,
    calcium_measured: 2.70,
    magnesium: 0.90,
    albumin_bcg: 54,
    c_reactive_protein: 1, // < 1.0
    total_protein: 89,
    esr: null,
    erythrocyte_count: 5.18,
    hemoglobin: 16.4,
    hematocrit: 0.49,
    mcv: 94.8,
    mch: 31.7,
    mchc: 33.4,
    rdw: 12.8,
    leucocyte_count: 9.35,
    neutrophils_pct: 56.9,
    neutrophil_absolute_count: 5.32,
    lymphocytes_pct: 30.5,
    lymphocytes_absolute_count: 2.85,
    monocytes_pct: 9.1,
    monocytes_absolute_count: 0.85,
    eosinophils_pct: 2.8,
    eosinophils_absolute_count: 0.26,
    basophils_pct: 0.7,
    basophils_absolute_count: 0.07,
    nlr: 1.87,
    platelets: 375
  },
  {
    name: "Matthew S Jacobs",
    code: 17,
    cortisol_nmol_l: 438,
    vitamin_d: 15,
    testosterone: 31.6,
    ck: 542,
    fasting_glucose: 4.5,
    hba1c: 5.4,
    hba1c_ifcc: 36,
    estimated_average_glucose: 6.0,
    urea: 7.1,
    creatinine: 103,
    egfr: 88,
    uric_acid: 0.36,
    s_glutamyl_transferase: 19,
    s_alanine_transaminase: 17,
    s_aspartate_transaminase: 26,
    lactate_dehydrogenase: 275,
    calcium_adjusted: 2.24,
    calcium_measured: 2.30,
    magnesium: 0.88,
    albumin_bcg: 43,
    c_reactive_protein: 3.1,
    total_protein: 79,
    esr: null,
    erythrocyte_count: 6.08,
    hemoglobin: 17.2,
    hematocrit: 0.51,
    mcv: 83.7,
    mch: 28.3,
    mchc: 33.8,
    rdw: 12.6,
    leucocyte_count: 15.01,
    neutrophils_pct: 73.5,
    neutrophil_absolute_count: 11.03,
    lymphocytes_pct: 18.1,
    lymphocytes_absolute_count: 2.71,
    monocytes_pct: 6.9,
    monocytes_absolute_count: 1.04,
    eosinophils_pct: 1.1,
    eosinophils_absolute_count: 0.17,
    basophils_pct: 0.4,
    basophils_absolute_count: 0.06,
    nlr: 4.07,
    platelets: 388
  },
  {
    name: "Michael Maseti",
    code: 18,
    cortisol_nmol_l: 497,
    vitamin_d: 11,
    testosterone: 28.8,
    ck: 380,
    fasting_glucose: 4.6,
    hba1c: 5.4,
    hba1c_ifcc: 36,
    estimated_average_glucose: 6.0,
    urea: 5.0,
    creatinine: 115,
    egfr: 78,
    uric_acid: 0.35,
    s_glutamyl_transferase: 61,
    s_alanine_transaminase: 32,
    s_aspartate_transaminase: 26,
    lactate_dehydrogenase: 242,
    calcium_adjusted: 2.34,
    calcium_measured: 2.48,
    magnesium: 0.87,
    albumin_bcg: 47,
    c_reactive_protein: 1, // < 1.0
    total_protein: 93,
    esr: null,
    erythrocyte_count: 5.13,
    hemoglobin: 14.9,
    hematocrit: 0.45,
    mcv: 88.3,
    mch: 29.0,
    mchc: 32.9,
    rdw: 12.2,
    leucocyte_count: 3.91,
    neutrophils_pct: 31.8,
    neutrophil_absolute_count: 1.24,
    lymphocytes_pct: 56.5,
    lymphocytes_absolute_count: 2.21,
    monocytes_pct: 8.4,
    monocytes_absolute_count: 0.33,
    eosinophils_pct: 2.8,
    eosinophils_absolute_count: 0.11,
    basophils_pct: 0.5,
    basophils_absolute_count: 0.02,
    nlr: 0.56,
    platelets: 276
  },
  {
    name: "Aden Oerson",
    code: 19,
    cortisol_nmol_l: 618,
    vitamin_d: 18,
    testosterone: 23.7,
    ck: 109,
    fasting_glucose: 4.6,
    hba1c: 5.8,
    hba1c_ifcc: 40,
    estimated_average_glucose: 6.6,
    urea: 8.2,
    creatinine: 98,
    egfr: 89, // > 89
    uric_acid: 0.31,
    s_glutamyl_transferase: 34,
    s_alanine_transaminase: 18,
    s_aspartate_transaminase: 19,
    lactate_dehydrogenase: 193,
    calcium_adjusted: 2.33,
    calcium_measured: 2.51,
    magnesium: 0.89,
    albumin_bcg: 49,
    c_reactive_protein: 3.5,
    total_protein: 78,
    esr: null,
    erythrocyte_count: 4.99,
    hemoglobin: 15.4,
    hematocrit: 0.46,
    mcv: 93.0,
    mch: 30.9,
    mchc: 33.2,
    rdw: 11.8,
    leucocyte_count: 6.26,
    neutrophils_pct: 49.8,
    neutrophil_absolute_count: 3.12,
    lymphocytes_pct: 39.3,
    lymphocytes_absolute_count: 2.46,
    monocytes_pct: 8.5,
    monocytes_absolute_count: 0.53,
    eosinophils_pct: 1.8,
    eosinophils_absolute_count: 0.11,
    basophils_pct: 0.6,
    basophils_absolute_count: 0.04,
    nlr: 1.27,
    platelets: 251
  },
  {
    name: "Riego Heath",
    code: 20,
    cortisol_nmol_l: 578,
    vitamin_d: 21,
    testosterone: 20.8,
    ck: 174,
    fasting_glucose: 5.2,
    hba1c: 5.3,
    hba1c_ifcc: 34,
    estimated_average_glucose: 5.8,
    urea: 6.0,
    creatinine: 93,
    egfr: 89, // > 89
    uric_acid: 0.38,
    s_glutamyl_transferase: 48,
    s_alanine_transaminase: 32,
    s_aspartate_transaminase: 21,
    lactate_dehydrogenase: 184,
    calcium_adjusted: 2.31,
    calcium_measured: 2.43,
    magnesium: 0.95,
    albumin_bcg: 46,
    c_reactive_protein: null,
    total_protein: null,
    esr: null,
    erythrocyte_count: 5.75,
    hemoglobin: 17.3,
    hematocrit: 0.50,
    mcv: 86.4,
    mch: 30.1,
    mchc: 34.8,
    rdw: 11.4,
    leucocyte_count: 5.84,
    neutrophils_pct: 41.8,
    neutrophil_absolute_count: 2.44,
    lymphocytes_pct: 46.6,
    lymphocytes_absolute_count: 2.72,
    monocytes_pct: 6.3,
    monocytes_absolute_count: 0.37,
    eosinophils_pct: 4.6,
    eosinophils_absolute_count: 0.27,
    basophils_pct: 0.7,
    basophils_absolute_count: 0.04,
    nlr: 0.90,
    platelets: 218
  },
  {
    name: "Aldrich Wichman",
    code: 21,
    cortisol_nmol_l: 541,
    vitamin_d: 44,
    testosterone: 28.5,
    ck: 176,
    fasting_glucose: 5.4,
    hba1c: 5.2,
    hba1c_ifcc: 33,
    estimated_average_glucose: 5.7,
    urea: 5.5,
    creatinine: 89,
    egfr: 89, // > 89
    uric_acid: 0.35,
    s_glutamyl_transferase: 34,
    s_alanine_transaminase: 25,
    s_aspartate_transaminase: 25,
    lactate_dehydrogenase: 220,
    calcium_adjusted: 2.25,
    calcium_measured: 2.49,
    magnesium: 0.88,
    albumin_bcg: 52,
    c_reactive_protein: 1, // < 1.0
    total_protein: 80,
    esr: null,
    erythrocyte_count: 5.22,
    hemoglobin: 16.1,
    hematocrit: 0.47,
    mcv: 89.3,
    mch: 30.8,
    mchc: 34.5,
    rdw: 12.1,
    leucocyte_count: 7.59,
    neutrophils_pct: 51.5,
    neutrophil_absolute_count: 3.91,
    lymphocytes_pct: 34.5,
    lymphocytes_absolute_count: 2.62,
    monocytes_pct: 6.7,
    monocytes_absolute_count: 0.51,
    eosinophils_pct: 6.9,
    eosinophils_absolute_count: 0.52,
    basophils_pct: 0.4,
    basophils_absolute_count: 0.03,
    nlr: 1.49,
    platelets: 346
  },
  {
    name: "Juane De Klerk",
    code: 22,
    cortisol_nmol_l: 416,
    vitamin_d: 25,
    testosterone: 22.9,
    ck: 181,
    fasting_glucose: 4.5,
    hba1c: 5.1,
    hba1c_ifcc: 32,
    estimated_average_glucose: 5.5,
    urea: 7.6,
    creatinine: 101,
    egfr: 89,
    uric_acid: 0.35,
    s_glutamyl_transferase: 11,
    s_alanine_transaminase: 20,
    s_aspartate_transaminase: 25,
    lactate_dehydrogenase: 195,
    calcium_adjusted: 2.32,
    calcium_measured: 2.48,
    magnesium: 0.82,
    albumin_bcg: 48,
    c_reactive_protein: 1, // < 1.0
    total_protein: 71,
    esr: null,
    erythrocyte_count: 4.84,
    hemoglobin: 15.1,
    hematocrit: 0.44,
    mcv: 90.7,
    mch: 31.2,
    mchc: 34.4,
    rdw: 12.1,
    leucocyte_count: 4.62,
    neutrophils_pct: 27.5,
    neutrophil_absolute_count: 1.27,
    lymphocytes_pct: 54.5,
    lymphocytes_absolute_count: 2.52,
    monocytes_pct: 10.4,
    monocytes_absolute_count: 0.48,
    eosinophils_pct: 6.7,
    eosinophils_absolute_count: 0.31,
    basophils_pct: 0.9,
    basophils_absolute_count: 0.04,
    nlr: 0.50,
    platelets: 183
  }
];

async function importBloodResults() {
  console.log('Starting blood results import...');

  for (const result of bloodResultsData) {
    try {
      // Map the name to the correct athlete code
      const athleteCode = nameToAthleteCodeMap[result.name];
      
      if (!athleteCode) {
        console.warn(`No athlete code mapping found for ${result.name}, skipping...`);
        continue;
      }

      // Convert athlete code to athlete_id by looking up the athlete
      const athleteId = await AthleteModel.getAthleteIdMapping(athleteCode);

      if (!athleteId) {
        console.warn(`Athlete with code ${athleteCode} not found in database, skipping...`);
        continue;
      }

      // Prepare the blood results data
      const bloodData = {
        AthleteId: athleteId, // Already a number from getAthleteIdMapping
        name: result.name,
        code: result.code,
        date: new Date().toISOString().split('T')[0], // Today's date
        lab_name: undefined, // New field - can be added later if needed
        test_method: undefined, // New field - can be added later if needed
        reference_ranges: undefined, // New field - can be added later if needed
        notes: undefined, // New field - can be added later if needed
        is_abnormal: false, // New field - default to false
        flagged_values: undefined, // New field - can be added later if needed
        cortisol_nmol_l: result.cortisol_nmol_l,
        vitamin_d: result.vitamin_d || undefined,
        testosterone: result.testosterone || undefined,
        ck: result.ck || undefined,
        fasting_glucose: result.fasting_glucose,
        hba1c: result.hba1c || undefined,
        hba1c_ifcc: result.hba1c_ifcc || undefined,
        estimated_average_glucose: result.estimated_average_glucose || undefined,
        urea: result.urea,
        creatinine: result.creatinine,
        egfr: result.egfr || undefined,
        uric_acid: result.uric_acid || undefined,
        s_glutamyl_transferase: result.s_glutamyl_transferase || undefined,
        s_alanine_transaminase: result.s_alanine_transaminase || undefined,
        s_aspartate_transaminase: result.s_aspartate_transaminase || undefined,
        lactate_dehydrogenase: result.lactate_dehydrogenase || undefined,
        calcium_adjusted: result.calcium_adjusted || undefined,
        calcium_measured: result.calcium_measured || undefined,
        magnesium: result.magnesium || undefined,
        albumin_bcg: result.albumin_bcg || undefined,
        c_reactive_protein: result.c_reactive_protein || undefined,
        total_protein: result.total_protein || undefined,
        esr: result.esr || undefined,
        erythrocyte_count: result.erythrocyte_count || undefined,
        hemoglobin: result.hemoglobin || undefined,
        hematocrit: result.hematocrit || undefined,
        mcv: result.mcv || undefined,
        mch: result.mch || undefined,
        mchc: result.mchc || undefined,
        rdw: result.rdw || undefined,
        leucocyte_count: result.leucocyte_count || undefined,
        neutrophils_pct: result.neutrophils_pct || undefined,
        neutrophil_absolute_count: result.neutrophil_absolute_count || undefined,
        lymphocytes_pct: result.lymphocytes_pct || undefined,
        lymphocytes_absolute_count: result.lymphocytes_absolute_count || undefined,
        monocytes_pct: result.monocytes_pct || undefined,
        monocytes_absolute_count: result.monocytes_absolute_count || undefined,
        eosinophils_pct: result.eosinophils_pct || undefined,
        eosinophils_absolute_count: result.eosinophils_absolute_count || undefined,
        basophils_pct: result.basophils_pct || undefined,
        basophils_absolute_count: result.basophils_absolute_count || undefined,
        nlr: result.nlr || undefined,
        platelets: result.platelets || undefined
      };

      // Insert the blood results
      console.log(`About to insert blood results for ${result.name} with AthleteId: ${bloodData.AthleteId}`);
      await BloodResultsModel.createBloodResults(bloodData);
      console.log(`Imported blood results for ${result.name} (Athlete Code: ${athleteCode})`);

    } catch (error) {
      console.error(`Failed to import blood results for ${result.name}:`, error);
    }
  }

  console.log('Blood results import completed!');
}

// Run the import if this script is executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
  importBloodResults()
    .then(() => {
      console.log('Import process finished successfully');
      process.exit(0);
    })
    .catch((error) => {
      console.error('Import process failed:', error);
      process.exit(1);
    });
}

export { importBloodResults };