# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - samapigene

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '22.x'

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint --if-present

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            dist
            .env
          key: build-${{ runner.os }}-${{ hashFiles('src/**/*', 'package*.json', 'vite.config.ts', 'scripts/**/*') }}
          restore-keys: |
            build-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Run tests
        run: npm run test --if-present

      - name: Prepare deployment files
        run: |
          mkdir -p deployment
          cp -r dist deployment/
          cp package.json deployment/
          cp package-lock.json deployment/
          cp .env deployment/ 2>/dev/null || true
          cp server.js deployment/ 2>/dev/null || true
          cp src/api/server.ts deployment/ 2>/dev/null || true
          cp tsconfig.json deployment/ 2>/dev/null || true
          cp ecosystem.config.js deployment/ 2>/dev/null || true
          cp web.config deployment/ 2>/dev/null || true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: deployment/
          retention-days: 7

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, build]
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: deployment

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B8F9BA4C7A7F4917AA743677E2433180 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1A590196BACA405194643BCFA21B3F2B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FBE07A0B787F415C84421F994E0A1CB6 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'samapigene'
          slot-name: 'Production'
          package: deployment/
          